site_name: "Modeling Healthcare Data with Graphs"
site_description: 'An undergraduate textbook on modeling healthcare data using graphs.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/modeling-healthcare-data/'
repo_url: 'https://github.com/dmccreary/modeling-healthcare-data'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About: about.md
  - Course Description: course-description.md

  - Learning Graph:
    - Introduction: learning-graph/index.md
    - Course Description Assessment: learning-graph/course-description-assessment.md
    - Concept List: learning-graph/concept-list.md
    - Quality Metrics: learning-graph/quality-metrics.md
    - Concept Taxonomy: learning-graph/concept-taxonomy.md
    - Taxonomy Distribution: learning-graph/taxonomy-distribution.md

  - MicroSims:
    - Introduction: sims/index.md
    - Graph Viewer: sims/graph-viewer/index.md
    - Codes: sims/codes/index.md
  - Prompts:
    - Introduction: prompts/index.md
    - Icon: prompts/icon.md
    - 1 - Analyze Course Description: prompts/01-run-course-description-analyzer.md
    - 2 - Learning Graph: prompts/02-learning-graph-generator.md
    - 3 - Install Viewer: prompts/03-run-the-learning-graph-viewer-installer-skill.md
  - Glossary: glossary.md
  - References: references.md
  - Feedback: feedback.md
  - How We Built This Site: how-we-built-this-site.md
  - License: license.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down

theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
extra_javascript:
   - js/extra.js
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX